Repository SuomixxXXxx/root-food-frontend, pull requests merged in 2024-11, with the labels that each got.

#67 Feauture/antonenko search enter by role
  src/components/Header.jsx
  src/components/SuggestionBox.jsx
  src/pages/ResultPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/dishItem.js
Labels: enhancement

#68 Feature/antonenkojwt token
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header.jsx
  src/components/ProtectedRoute.jsx
  src/components/SideBarWorker.jsx
  src/pages/DashboardProductPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/categories.js
Labels: enhancement

#69 Feature/add web socket
  package-lock.json
  package.json
  src/App.jsx
  src/components/DashboardOrderCard.jsx
  src/pages/DashboardOrderPage.jsx
  src/redux/slices/order.js
  src/redux/store.js
Labels: enhancement

#70 Feature/constants
  src/axios.js
  src/components/CardCategory.jsx
  src/components/DashboardProductCard.jsx
  src/components/Header.jsx
  src/components/OrderBox.jsx
  src/components/ProductCard.jsx
  src/components/ProtectedRoute.jsx
  src/components/SidebarCategory.jsx
  src/components/SuggestionBox.jsx
  src/constants.js
  src/pages/CategoryPage.jsx
  src/pages/LandingPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ProductPage.jsx
  src/pages/ResultPage.jsx
  src/pages/SignupPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/cart.js
  src/redux/slices/categories.js
  src/redux/slices/dishItem.js
  src/redux/slices/order.js
Labels: enhancement

#74 Feature/header update
  package-lock.json
  package.json
  src/App.css
  src/assets/aqua.svg
  src/components/Header.jsx
  src/components/SuggestionBox.jsx
  src/constants.js
  src/index.css
  src/redux/slices/cart.js
  tailwind.config.js
Labels: improvement

#78 Feature/add product antonenko
  src/App.jsx
  src/assets/images/uploadImage.png
  src/components/DashboardProductCard.jsx
  src/constants.js
  src/pages/DashboardProductPage.jsx
  src/redux/slices/categories.js
  src/redux/slices/dishItem.js
Labels: enhancement

#79 Feature/Footer
  src/App.jsx
  src/components/Footer.jsx
  src/index.css
  src/pages/LandingPage.jsx
Labels: enhancement

#80 Fix/stompjs
  src/redux/slices/order.js
Labels: improvement

#83 Feature/Update cart page
  src/components/Header.jsx
  src/components/OrderBox.jsx
  src/components/PaymentBox.jsx
  src/components/ProductCard.jsx
  src/index.css
  src/pages/CartPage.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
  src/pages/ResultPage.jsx
  src/redux/slices/cart.js
Labels: improvement

#84 Feature/Update cart page (clear cart)
  src/components/OrderBox.jsx
Labels: improvement

#88 Feature/del db pr card
  src/assets/images/food-background-images-3.jpg
  src/components/DashboardProductCard.jsx
  src/pages/DashboardProductPage.jsx
  src/redux/slices/dishItem.js
Labels: enhancement

#89 Feature/update category card
  src/components/CardCategory.jsx
  src/components/Header.jsx
  src/components/OrderBox.jsx
  src/components/PaymentBox.jsx
  src/components/ProductCard.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
Labels: improvement

#90 Feature/home page
  package-lock.json
  package.json
  src/App.jsx
  src/assets/homeImages/Component 19.svg
  src/components/Header.jsx
  src/components/ProductCard.jsx
  src/index.css
  src/pages/HomePage.jsx
Labels: enhancement

#91 Validate dashboard product card
  src/components/DashboardProductCard.jsx
  src/pages/DashboardProductPage.jsx
Labels: enhancement

#93 Feature/api update
  README.md
  src/App.jsx
  src/assets/readme/DorderPage.png
  src/assets/readme/Payment.png
  src/assets/readme/addComponent.png
  src/assets/readme/cart.png
  src/assets/readme/cartFun.png
  src/assets/readme/cartMinus.png
  src/assets/readme/cartPage(mobile).png
  src/assets/readme/cartPage.png
  src/assets/readme/category.png
  src/assets/readme/categoryPage(mobile).png
  src/assets/readme/categoryPage.png
  src/assets/readme/dishItem.png
  src/assets/readme/editComponent.png
  src/assets/readme/emptyCart.png
  src/assets/readme/homePage1(mobile).png
  src/assets/readme/homePage1.png
  src/assets/readme/homePage2(mobile).png
  src/assets/readme/homePage2.png
  src/assets/readme/login.png
  src/assets/readme/loginPage.png
  src/assets/readme/logout.png
  src/assets/readme/noAuth.png
  src/assets/readme/productPage(mobile).png
  src/assets/readme/productPage1.png
  src/assets/readme/productPage2.png
  src/assets/readme/search.png
  src/assets/readme/signup.png
  src/assets/readme/signupPage.png
  src/assets/readme/successPayment.png
  src/assets/readme/tokenAndPersistCar.png
  src/axios.js
  src/components/DashboardProductCard.jsx
  src/constants.js
  src/pages/CartPage.jsx
  src/pages/CategoryPage.jsx
  src/pages/HomePage.jsx
  src/pages/ProductPage.jsx
  src/pages/ResultPage.jsx
  src/redux/slices/auth.js
Labels: documentation, improvement
