Repository SuomixxXXxx/root-food-frontend, pull requests merged in 2024-10, with the labels that each got.

#32 Feature/auth api
  package-lock.json
  package.json
  src/App.jsx
  src/axios.js
  src/components/Header.jsx
  src/main.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/dishItem.js
  src/redux/store.js
Labels: enhancement

#33 Feature/Antonenko-page-with-products
  src/App.jsx
  src/components/Header.jsx
  src/components/ProductCard.jsx
  src/components/SidebarCategory.jsx
  src/pages/ProductPage.jsx
  tailwind.config.js
Labels: enhancement

#36 Feature/fetch categories
  src/App.jsx
  src/components/CardCategory.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/categories.js
  src/redux/store.js
Labels: enhancement

#39 Feature/fetch dishes by category
  src/App.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/dishItem.js
Labels: enhancement

#40 Revert "Feature/fetch dishes by category"
  src/App.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/dishItem.js
Labels: invalid

#41 Feature/fetch dishes by category
  src/App.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/pages/ProductPage.jsx
  src/redux/slices/auth.js
  src/redux/slices/dishItem.js
Labels: enhancement

#46 Feature/cart persist items
  package-lock.json
  package.json
  src/components/Header.jsx
  src/components/OrderBox.jsx
  src/components/PaymentBox.jsx
  src/components/ProductCard.jsx
  src/main.jsx
  src/pages/CartPage.jsx
  src/pages/ProductPage.jsx
  src/redux/slices/cart.js
  src/redux/store.js
Labels: enhancement

#48 Feature/dashboard product page
  src/App.jsx
  src/components/DashboardProductCard.jsx
  src/components/SideBarWorker.jsx
  src/pages/CategoryPage.jsx
  src/pages/DashboardPage.jsx
  src/pages/DashboardProductPage.jsx
Labels: enhancement

#49 Feature/order request
  src/components/Header.jsx
  src/components/Modal.jsx
  src/components/PaymentBox.jsx
  src/components/ProductCard.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/redux/slices/cart.js
Labels: enhancement

#50 OrdersWorkers
  src/App.jsx
  src/components/DashboardOrderCard.jsx
  src/components/Header.jsx
  src/components/SideBarWorker.jsx
  src/pages/DashboardOrderPage.jsx
  src/pages/DashboardProductPage.jsx
Labels: enhancement

#51 Feature/Readme
  README.md
  src/assets/readme/cart.png
  src/assets/readme/cartFun.png
  src/assets/readme/cartMinus.png
  src/assets/readme/category.png
  src/assets/readme/dishItem.png
  src/assets/readme/emptyCart.png
  src/assets/readme/login.png
  src/assets/readme/logout.png
  src/assets/readme/noAuth.png
  src/assets/readme/signup.png
  src/assets/readme/successPayment.png
  src/assets/readme/tokenAndPersistCar.png
  src/components/SideBarWorker.jsx
Labels: documentation

#52 Update README.md
  README.md
Labels: documentation

#53 Update README.md
  README.md
Labels: documentation

#58 Feauture/update card
  src/components/DashboardProductCard.jsx
  src/components/Modal.jsx
  src/components/ProductCard.jsx
Labels: enhancement

#59 Hotfix/ добавила модальное окно для работника
  src/components/DashboardProductCard.jsx
Labels: bug

#60 Feature/antonenko orderbox and search
  src/App.jsx
  src/components/Header.jsx
  src/components/OrderBox.jsx
  src/pages/CartPage.jsx
  src/pages/ResultPage.jsx
  src/redux/slices/dishItem.js
  src/redux/store.js
Labels: enhancement

#62 feat: resolve conflict
  src/App.jsx
  src/components/SidebarCategory.jsx
  src/pages/CategoryPage.jsx
  src/redux/slices/auth.js
Labels: enhancement

#61 ALPHA 0.3
  README.md
  package-lock.json
  package.json
  src/App.jsx
  src/assets/readme/cart.png
  src/assets/readme/cartFun.png
  src/assets/readme/cartMinus.png
  src/assets/readme/category.png
  src/assets/readme/dishItem.png
  src/assets/readme/emptyCart.png
  src/assets/readme/login.png
  src/assets/readme/logout.png
  src/assets/readme/noAuth.png
  src/assets/readme/signup.png
  src/assets/readme/successPayment.png
  src/assets/readme/tokenAndPersistCar.png
  src/components/DashboardOrderCard.jsx
  src/components/DashboardProductCard.jsx
  src/components/Header.jsx
  src/components/Modal.jsx
  src/components/OrderBox.jsx
  src/components/PaymentBox.jsx
  src/components/ProductCard.jsx
  src/components/SideBarWorker.jsx
  src/main.jsx
  src/pages/CartPage.jsx
  src/pages/CategoryPage.jsx
  src/pages/DashboardOrderPage.jsx
  src/pages/DashboardPage.jsx
  src/pages/DashboardProductPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ProductPage.jsx
  src/pages/ResultPage.jsx
  src/pages/SignupPage.jsx
  src/redux/slices/cart.js
  src/redux/slices/dishItem.js
  src/redux/store.js
Labels: enhancement
